package tree;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lestat Alvarez Quintana Ordiz
 */
public class TreeGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TreeGUI.class.getName());

    /**
     * Creates new form TreeGUI
     */
    public TreeGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        treeNumber = new javax.swing.JTextField();
        treeSpecie = new javax.swing.JTextField();
        treeLocation = new javax.swing.JTextField();
        treeRegion = new javax.swing.JTextField();
        addTree = new javax.swing.JButton();
        treeRemove = new javax.swing.JButton();
        showTrees = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showAll = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tree Number");

        jLabel2.setText("Tree Specie");

        jLabel3.setText("Tree Location");

        jLabel4.setText("Region");

        treeNumber.setText("(ie. 0)");
        treeNumber.addActionListener(this::treeNumberActionPerformed);

        treeSpecie.setText("(ie. Pine)");
        treeSpecie.addActionListener(this::treeSpecieActionPerformed);

        treeLocation.setText("(ie. NCI Campus)");
        treeLocation.addActionListener(this::treeLocationActionPerformed);

        treeRegion.setText("(Ie. Ireland)");
        treeRegion.addActionListener(this::treeRegionActionPerformed);

        addTree.setText("Add");
        addTree.addActionListener(this::addTreeActionPerformed);

        treeRemove.setText("Remove");
        treeRemove.addActionListener(this::treeRemoveActionPerformed);

        showTrees.setText("Show Trees");
        showTrees.addActionListener(this::showTreesActionPerformed);

        showAll.setColumns(20);
        showAll.setRows(5);
        showAll.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                showAllAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(showAll);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showTrees, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(treeNumber)
                                            .addComponent(treeSpecie)
                                            .addComponent(treeLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                            .addComponent(treeRegion))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                                        .addComponent(treeRemove))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(addTree)))))
                        .addGap(210, 210, 210))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(treeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(treeSpecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(treeLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(treeRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(addTree)
                        .addGap(27, 27, 27)
                        .addComponent(treeRemove)))
                .addGap(18, 18, 18)
                .addComponent(showTrees)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void treeNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treeNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_treeNumberActionPerformed

    private void treeSpecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treeSpecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_treeSpecieActionPerformed

    private void treeLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treeLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_treeLocationActionPerformed

    private void treeRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treeRegionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_treeRegionActionPerformed

    private void addTreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTreeActionPerformed

    private void treeRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treeRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_treeRemoveActionPerformed

    private void showTreesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTreesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showTreesActionPerformed

    private void showAllAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_showAllAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_showAllAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TreeGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea showAll;
    private javax.swing.JButton showTrees;
    private javax.swing.JTextField treeLocation;
    private javax.swing.JTextField treeNumber;
    private javax.swing.JTextField treeRegion;
    private javax.swing.JButton treeRemove;
    private javax.swing.JTextField treeSpecie;
    // End of variables declaration//GEN-END:variables
}
